name: Compile c++

on:
  push

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt Install gcc

      - name: Compile the file
        run: g++ file.cpp